### ISSUE TITLE
Receiving "No module named 'moviepy'" when trying to rebuild catalog

### ISSUE THREAD

**Issue by JonnyGators** [shane-mason/FieldStation42#10]
I'm still just starting to set this up, I assume I need to build a catalog to start with, so I tried running the python3 station_42.py --rebuild_catalog command.  It spit out a bunch of text that ended with the No module named 'moviepy' error.  

I re-read over all documentation searching for any mention of moviepy, what it is, or any requirement/prerequisit for this.  I have found none.  This has caught me completely by surprise, as nowhere was this mentioned in the documentation.  Was it supposed to come through some other way?

I reviewed and confirmed that I've met all pre-requisits in that I have mpv and python3 installed and up to date.  The cloned repository is also current and up to date.  I'm still not sure how I can be missing something required.

I further searched for moviepy, and how to install it.  All documentation points to running pip3 install moviepy.  However, running this command on a prompt in raspbian results in a bunch of gibberish to the effect of the environment being externally managed.  Not sure what this means, or why this means it cannot execute the installation I requested.  It suggests instead trying apt install python3-xyz where xyz is the package you are trying to install.

Running the suggested command of sudo apt install python3-moviepy results in an error of "Package 'python3-moviepy' has no installation candidate"

I'm completely lost at this point.  Please advise.

**Comment by shane-mason** [comment]
You ran the install script? Did you activate the python virtual environment before your ran station42? You need to run something like:

`source env/bin/activate`

That needs to be ran at least once in the shell before any python commands. You can add that to your login script so you don't have to enter it on each shell.

**Comment by shane-mason** [comment]
Also - station_42 will look to see if there is an existing catalog.bin file for the station and rebuild the catalog if there isn't. I am looking having it do an automatic 'quick look' for changes and then automatically updating the catalog if there have been changes.

**Comment by JonnyGators** [comment]
Ok, all good to know things.
Running python3 station_42.py is resulting in the following

(env) jgata@raspberrypi:~/projects/FieldStation42 $ python3 station_42.py
False
Traceback (most recent call last):
  File "/home/jgata/projects/FieldStation42/station_42.py", line 255, in <module>
    from confs.fieldStation42_conf import main_conf
  File "/home/jgata/projects/FieldStation42/confs/fieldStation42_conf.py", line 29, in <module>
    load_json_stations()
  File "/home/jgata/projects/FieldStation42/confs/fieldStation42_conf.py", line 26, in load_json_stations
    main_conf['stations'] = sorted(stations, key=lambda station: station['channel_number'])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgata/projects/FieldStation42/confs/fieldStation42_conf.py", line 26, in <lambda>
    main_conf['stations'] = sorted(stations, key=lambda station: station['channel_number'])
                                                                 ~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'channel_number'


I'm not finding any reference in the documentation for a 'channel_number', so I'm not seeing what I overlooked.

**Comment by shane-mason** [comment]
Oh yeah! I just added this in the last week. Good find! Who does quality control around here anyway?? ;) Quick fix: add a line like this in your config:

`"channel_number": 1,`

all the example json files in `confs/examples` contain that line. I would recommend using one of those as the starting point. Make sure you have done a fresh `git pull` to get all the latest goodies I have added.

This feature was added because I did't have a way of specifiying what order I wanted the channels to come in - soon I will add an overlay option to show the channel number when you turn the channel (my TV from '86 does that with a digital overlay)

**Comment by shane-mason** [comment]
Updated the documents with more information on that configuration option.

**Comment by JonnyGators** [comment]
Ok, that makes sense, I cleared that setting out since the documentation didn't include it or explain it, guess I should've left it alone.

Now I'm consistently getting stuck on the catalog build.  So far I've only included 1 TV programs folder and 1 commercial folder to start with to build a single test channel that just plays episodes from the same show with commercials to pad them out, so it isn't a huge catalog to build.  But it seems to always get stuck at the same point.  I don't think it's a hardware issue, otherwise the failure point wouldn't be so consistent.  I don't think it's a specific bad file it's trying to catalog - I renamed the file it got stuck at, and then it got stuck at the next file.  I renamed my subfolders to be shorter in case I was running into a path size limitation, and it gets stuck at a different point after that change, but again, at the same consistent point.  Something is making it crash.

When it happens, my putty session into the terminal becomes unresponsive, and eventually times out.  Nothing is displaying on the screen (currently it's connected to an official Pi LCD, once I get things working as I want I'll move it over to a TV), my power button that's connected to a gpio becomes unresponsive, will not do a shutdown or power on, I'm not sure if it's powered on in a completely stuck state with no screen, or if it's powered off in some bad state that it won't turn back on, I have to pull the plug and plug it back in to get it to turn on again.

After a reboot, whether or not I run it with or without a --rebuild_catalog, it starts the catalog build, so whatever partially ran before doesn't leave it in a state of having a catalog, so it starts a new/first build.

Any idea how to troubleshoot what's crashing out the catalog building process?

**Comment by shane-mason** [comment]
Let me see if I understand correctly: its going through the files and adding them to the catalog and then it crashes and stops updating the screen? 

I am running about 800 GB of movie files - takes about 3 to 4 minutes to process the catalog - so it shouldn't be a memory issue that you are seeing. File path length shouldn't be an issue.  I am stumped. Its at different parts of the catalog this happens?

**Comment by JonnyGators** [comment]
If I don't change anything, it's at the same part of the catalog.

If I change a foldername or filename, it changes the part of the catalog.

I am creating folders in my test channel folder, and mounting them to folders on my media server, rather than copying things directly to the microsd card.  

I was testing with a single TV show that has 8 seasons, I removed a few of the season folders out of my folder to allow it to finish, and that worked to get it past that point.

My problem now is I need to find a good collection of various length commercials, I pointed to a folder I have of a few crazy eddie commercials, but it now bombs out trying to make hour long blocks.  I found a torrent with more ads.

I'll keep poking around and keep you posted, and let me know if you think of what might have caused it.  I'm concerned as I ramp this up and build up a library I'm going to run into this again.

**Comment by shane-mason** [comment]
yeah - it needs a variety of commercials and bumps. I like bumps because they can be 2 or 3 second long station identifications.  

I wonder if network issues were at play? I am using a local hard disk - but haven't tested at scale past the 800 GB of shows that I built out for this. Let me think on how I can do some synthetic testing.

**Comment by JonnyGators** [comment]
Well, if you want, but at this point feel free to hold off until I have more details.  I'll troubleshoot some more and try to dial more into it.  Sorry to be reaching out so much, you've been so great.

**Comment by Devineavenger** [comment]
Issue with Raspberry Pi I also have (think it's a python issue there, something about ram overflow) For now I have the whole thing on a removable HDD. I move it to my computer to rebuild the catalog, then I move it to the pi to do the scheduling. And as of yet, that scheduling is not working for me either. I built up like 20 GB of commercials, in increments of seconds. Still no go. I only saw it complete once, by who knows what miracle. The problem I see is that there is no leeway in the hour long blocks it tries to schedule.

**Comment by Devineavenger** [comment]
Using a RPi 4 with 2gb of ram and one pi 4 with 4gb of ram. both break. one lasts about 20 episodes of scanning, the other about 35 episodes before they break. Using Python 3.12

**Comment by shane-mason** [comment]
That doesn't sound right - I was running it on an orange pi zero and the scanning was working fine. What is your read/write rate to the disks?

**Comment by shane-mason** [comment]
@Devineavenger - quick question on this:

> I built up like 20 GB of commercials, in increments of seconds

Are those all in mp4 format? I was just looking at another features request to add additional file types and made me think about your commercial issue - it may not be reading all the content you have.

**Comment by Devineavenger** [comment]
All the content went through handbrake, so all of it, from bump and commercials to content is h264 + aac 2.0, mp4

**Comment by shane-mason** [comment]
Then something is strange, because you shouldn't have gotten errors that it couldn't find content under 15.1 seconds if you have content that ranges in multiples of seconds. Did you look at the catalog generation logs to make sure that it was picking up the content in both commercial and bump?

**Comment by Devineavenger** [comment]
Well now that you mention it, it picks it up and shows it in the output when building the catalog, but in the .bin file, there are only a few entries. Odd... My bumps and commercials are arranged in subfolders inside their respective folders and it seems to only add one of those subfolders to the catalog_path file.

**Comment by shane-mason** [comment]
This is important point and I think we just solved the mystery - here is the code for subdirectory inspection
```
  subs = [ f.path for f in os.scandir(tag_dir) if f.is_dir() ]
  for sub in subs:
      self._l.info("Found sub-directory " + sub)
      file_list = glob.glob(f"{sub}/*.mp4")
      
      self.clip_index[tag] = self._process_media(file_list, tag)
```

This worked in some basic testing - but now that I look at it, I see exactly what is happening. In my test case, I just put all the commercials in a single sub-directory under commercials and it worked. Here is the problem:

` file_list = glob.glob(f"{sub}/*.mp4")` is overwriting all previous files for each subdir - it should be `file_list += glob.glob(f"{sub}/*.mp4")`

I'll make the fix.

**Comment by shane-mason** [comment]
Okay - its committed. With this and the fix to @Devineavenger issue last night that made the break scheduler more flexible, this should fix the commercial break issue.

**Comment by shane-mason** [comment]
If this works for you, I'll close this issue out.

**Comment by Devineavenger** [comment]
Tested, works.

**Comment by shane-mason** [comment]
There were some other issues with it - I've tested with more scenarios and it should handle them all now. Cheers!

**Comment by Devineavenger** [comment]
Working.

**Comment by shane-mason** [comment]
Closing this as resolved - the original issue was around dependencies, and the new install script should take care of that. Cheers!
