### ISSUE TITLE
Enhancement: add simple playlist loop support

### ISSUE THREAD

**Issue by manodory** [shane-mason/FieldStation42#25]
It would be great to have support for a video loop support for a specific channel - 
Let's say I'm creating a folder named 'loop' under channel_1, so the catalog build will just play the folder content in a loop regardless of any planned schedule. This is very usefull for creating some old cable channels simulation, such as the videoflex channel or the public message board channel. 
 BTW, just found out Labels, but I cant find a way to edit...

Thanks a lot!

**Comment by shane-mason** [comment]
Starting this now - will use alpha-numeric ordering in content folder.

**Comment by shane-mason** [comment]
One complication here: it needs to play on time still? Meaning, everytime you switch to it, it should be playing as though it had continued playing the entire time? Meaning: are these actual shows where continuity matters? In most of the scenarios I can think of, this is not the case:

* Informational channels - community announcement screens and some short clips played in order
* Ambiance channels - playing things like a beach sunrise, yule log burning etc

For all of these, state doesn't really matter, so each time someone turned to the channel, you could just start playing from a random place and it wouldn't matter. Is that the case with your request, or does continuity matter? 

I think is probably does in any case for a convincing simulation. You wouldn't want to do a fast switch between channels and a log that just started burning is burned all the way through when you switch back.

**Comment by manodory** [comment]
I'd rather have it continuity aware, as you said, for a much convincing simutation.
I also think about cases wehre I need an actual video shot running in loop, having it playing randomly qould break the experience...

**Comment by shane-mason** [comment]
Just for clarity - the station will hold one content directory and then it will loop content from that directory 24 hours per day. You weren't thinking of different schedules per hour for this, right?

**Comment by shane-mason** [comment]
The first version of this is ready for review.

**Comment by shane-mason** [comment]
This is completed and documented under the experimental feature section of the wiki.
