### ISSUE TITLE
Best way to connect Raspberry Pi to Analog TV

### ISSUE THREAD

**Issue by BLDY609c** [shane-mason/FieldStation42#38]
This is more for guidance and general information to other individuals who are interested in the project. 
How is the raspberry pi connected to the tv? HDMI to RF? RCA soldered to the board and configured thru raspi-config? And how is the audio transmitted? The wiring diagram is splendid for the button/screen, but some beginners may have an issue deciding what to pursue.

**Comment by shane-mason** [comment]
Good callout - will add to documentation. For reference: I am using an HDMI-to-RF converter box and it does okay. Audio is transmitted over the same line.
