### ISSUE TITLE
File type playback other than .mp4

### ISSUE THREAD

**Issue by JonnyGators** [shane-mason/FieldStation42#9]
First, I'd like to thank you for creating this project, and taking the time to update and enhance the installation instructions from my youtube comment feedback.  I have been pondering doing similar things with a Pi myself, and this aligns quite closely with my Pi goals.  I am quite excited about this project, and what it can already do.

I notice in the documentation, you already noted "The program expects content to have an mp4 extension, though this could easily be extended if there are use cases."  I already have a large library of various video file types, so this extension would be so helpful if it isn't too much trouble.  In addition to mp4, my library includes .mkv, .avi, .mpg/mpeg, m4v.

This might be separate, but it also relate to playback media type.  Adding the capability to also schedule in channels, or blocks in channels to playback live TV from a network TV tuner could open up further enhancements to this project.  This youtube video shows how a desktop shortcut can be made in Ubuntu linux to playback a TV channel in mpv player, I have tested that this also works is Raspian - https://www.youtube.com/watch?v=qbkU70-fH3o  

I see this opening up 2 possibilities in this project:
1. The TV can be configured with a mixture of the current pre-recorded generated channels, and live channels - that is, add a channel that just simply calls on a live channel 24/7.
2. Add in the capability to use live TV for blocks of the schedule.  For example, add in current evening news into a network's generated schedule, instead of pre-recorded new programs to emulate the daily schedule.  Or if you receive the "Antenna TV" network on a sub-channel, use it's Jonny Carson rerun in your NBC channel instead of relying on a local storage of Carson recordings.  With numerous subchannels that rerun classic material, or things like BUZZR that runs gameshows, it allows one to program some reruns and gameshows into their schedule, without having to rely on libraries for all things.

I suppose this could be a heavy lift, as it doesn't fall into your scheme of calculating time blocks and inserting commercials to make a time block, there would have to be a way to signal just play this url for this block of time.  And I understand if this idea falls outside of your vision and doesn't exactly inspire you to put the time into implementing it.  Just wanted to throw that out there.

Again, thanks so much for this project, and your time and attention to putting together clear and easy to follow documentation.  This has all been greatly appreciated.

**Comment by shane-mason** [comment]
For supporting multiple file types: as long as movie py and mpv supports them, it should be no problem. Anything that FFMPEG supports should work then. I'll take this one up first.

For streaming, I've thought a lot about this one too. Especially since content distribution is a concern, this could make a good feature. I'll think over this one in the next days.

**Comment by shane-mason** [comment]
@JonnyGators -  working on this now. Should be fast, but I want to generate some test files to run through.

**Comment by shane-mason** [comment]
Yep - super simple - I added support for the following:

`self.supported_formats = ["mp4", "mpg", "avi", "mov", "mkv"]`

I'll test it tomorrow and then commit.

**Comment by shane-mason** [comment]
This is completed! It now looks for: "mp4", "mpg", "mpeg", "avi", "mov", "mkv" 

Cheers!
